services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/assets:/app/assets # Syncs your trained .pkl models

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
